<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('restaurants')->insert([
            [
                'id' => 1,
                'name' => 'Gourmet Paradise',
                'cuisine_type' => 'Italian',
                'location' => 'Food City',
                'detail_address' => '123 Pasta Lane',
                'phone' => '123-456-7890',
                'email' => 'contact@gourmetparadise.com',
                'website' => 'www.gourmetparadise.com',
                'rating' => 4.5,
                'profile_image' => 'assets/restaurants/restaurant_pic_1.png',
                'cover_image' => 'assets/covers/cover_pic_1.png',
                'bio' => 'A haven for Italian cuisine lovers',
                'is_open' => true,
                'has_delivery' => true,
            ],
            [
                'id' => 2,
                'name' => 'Healthy Bites',
                'cuisine_type' => 'Vegetarian',
                'location' => 'Veggie Town',
                'detail_address' => '456 Green St',
                'phone' => '987-654-3210',
                'email' => 'info@healthybites.com',
                'website' => 'www.healthybites.com',
                'rating' => 4.7,
                'profile_image' => 'assets/restaurants/restaurant_pic_2.png',
                'cover_image' => 'assets/covers/cover_pic_2.png',
                'bio' => 'Delicious vegetarian meals',
                'is_open' => true,
                'has_delivery' => false,
            ],
            [
                'id' => 3,
                'name' => 'Sushi World',
                'cuisine_type' => 'Japanese',
                'location' => 'Tokyo City',
                'detail_address' => '789 Sushi Blvd',
                'phone' => '555-123-4567',
                'email' => 'hello@sushiworld.com',
                'website' => 'www.sushiworld.com',
                'rating' => 4.9,
                'profile_image' => 'assets/restaurants/restaurant_pic_3.png',
                'cover_image' => 'assets/covers/cover_pic_3.png',
                'bio' => 'Authentic Japanese sushi',
                'is_open' => false,
                'has_delivery' => true,
            ],
            [
                'id' => 4,
                'name' => 'Burger Hub',
                'cuisine_type' => 'American',
                'location' => 'Fast Food City',
                'detail_address' => '101 Burger Ave',
                'phone' => '111-222-3333',
                'email' => 'contact@burgerhub.com',
                'website' => 'www.burgerhub.com',
                'rating' => 4.2,
                'profile_image' => 'assets/restaurants/restaurant_pic_4.png',
                'cover_image' => 'assets/covers/cover_pic_4.png',
                'bio' => 'Best burgers in town',
                'is_open' => true,
                'has_delivery' => true,
            ],
            [
                'id' => 5,
                'name' => 'Curry Palace',
                'cuisine_type' => 'Indian',
                'location' => 'Curry Town',
                'detail_address' => '202 Spice Rd',
                'phone' => '222-333-4444',
                'email' => 'support@currypalace.com',
                'website' => 'www.currypalace.com',
                'rating' => 4.8,
                'profile_image' => 'assets/restaurants/restaurant_pic_5.png',
                'cover_image' => 'assets/covers/cover_pic_5.png',
                'bio' => 'Exquisite Indian flavors',
                'is_open' => true,
                'has_delivery' => false,
            ],
            [
                'id' => 6,
                'name' => 'Taco Fiesta',
                'cuisine_type' => 'Mexican',
                'location' => 'Taco City',
                'detail_address' => '303 Fiesta Lane',
                'phone' => '333-444-5555',
                'email' => 'info@tacofiesta.com',
                'website' => 'www.tacofiesta.com',
                'rating' => 4.6,
                'profile_image' => 'assets/restaurants/restaurant_pic_6.png',
                'cover_image' => 'assets/covers/cover_pic_6.png',
                'bio' => 'Celebrating Mexican cuisine',
                'is_open' => false,
                'has_delivery' => true,
            ],
            [
                'id' => 7,
                'name' => 'Bistro Delights',
                'cuisine_type' => 'French',
                'location' => 'Paris City',
                'detail_address' => '404 Bistro Blvd',
                'phone' => '444-555-6666',
                'email' => 'reservations@bistrodelights.com',
                'website' => 'www.bistrodelights.com',
                'rating' => 4.7,
                'profile_image' => 'assets/restaurants/restaurant_pic_7.png',
                'cover_image' => 'assets/covers/cover_pic_7.png',
                'bio' => 'A taste of France',
                'is_open' => true,
                'has_delivery' => true,
            ],
            [
                'id' => 8,
                'name' => 'Dragon\'s Breath',
                'cuisine_type' => 'Chinese',
                'location' => 'China Town',
                'detail_address' => '505 Dragon St',
                'phone' => '555-666-7777',
                'email' => 'contact@dragonsbreath.com',
                'website' => 'www.dragonsbreath.com',
                'rating' => 4.3,
                'profile_image' => 'assets/restaurants/restaurant_pic_8.png',
                'cover_image' => 'assets/covers/cover_pic_8.png',
                'bio' => 'Authentic Chinese cuisine',
                'is_open' => true,
                'has_delivery' => false,
            ],
            [
                'id' => 9,
                'name' => 'Mediterranean Magic',
                'cuisine_type' => 'Mediterranean',
                'location' => 'Med Town',
                'detail_address' => '606 Olive Rd',
                'phone' => '666-777-8888',
                'email' => 'hello@medmagic.com',
                'website' => 'www.medmagic.com',
                'rating' => 4.9,
                'profile_image' => 'assets/restaurants/restaurant_pic_9.png',
                'cover_image' => 'assets/covers/cover_pic_9.png',
                'bio' => 'Mediterranean delights',
                'is_open' => false,
                'has_delivery' => true,
            ],
            [
                'id' => 10,
                'name' => 'Dessert Haven',
                'cuisine_type' => 'Desserts',
                'location' => 'Sweet City',
                'detail_address' => '707 Sugar Lane',
                'phone' => '777-888-9999',
                'email' => 'info@desserthaven.com',
                'website' => 'www.desserthaven.com',
                'rating' => 4.8,
                'profile_image' => 'assets/restaurants/restaurant_pic_10.png',
                'cover_image' => 'assets/covers/cover_pic_10.png',
                'bio' => 'Heavenly desserts',
                'is_open' => true,
                'has_delivery' => true,
            ],
        ]);
    }
}
