<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Jane Smith',
                'user_name' => 'janesmith',
                'email' => 'jane.smith@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'female',
                'location_name' => 'New York',
                'head_line_bio' => 'Tech enthusiast and blogger',
                'profile_image' => 'assets/profiles/profile_pic_1.png',
                'total_orders' => 10,
                'membership_level' => 'Gold',
                'email_marketing' => true,
                'online_status' => true,
                'keep_signed_in' => true,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alice Johnson',
                'user_name' => 'alicejohnson',
                'email' => 'alice.johnson@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'female',
                'location_name' => 'San Francisco',
                'head_line_bio' => 'Digital artist and designer',
                'profile_image' => 'assets/profiles/profile_pic_2.png',
                'total_orders' => 5,
                'membership_level' => 'Silver',
                'email_marketing' => false,
                'online_status' => false,
                'keep_signed_in' => false,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bob Brown',
                'user_name' => 'bobbrown',
                'email' => 'bob.brown@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'location_name' => 'Los Angeles',
                'head_line_bio' => 'Professional photographer',
                'profile_image' => 'assets/profiles/profile_pic_3.png',
                'total_orders' => 8,
                'membership_level' => 'Gold',
                'email_marketing' => true,
                'online_status' => true,
                'keep_signed_in' => true,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Charlie Davis',
                'user_name' => 'charliedavis',
                'email' => 'charlie.davis@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'location_name' => 'Chicago',
                'head_line_bio' => 'Freelance writer',
                'profile_image' => 'assets/profiles/profile_pic_4.png',
                'total_orders' => 12,
                'membership_level' => 'Platinum',
                'email_marketing' => false,
                'online_status' => true,
                'keep_signed_in' => false,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Deborah Harris',
                'user_name' => 'deborahharris',
                'email' => 'deborah.harris@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'female',
                'location_name' => 'Miami',
                'head_line_bio' => 'Fitness coach',
                'profile_image' => 'assets/profiles/profile_pic_5.png',
                'total_orders' => 20,
                'membership_level' => 'Gold',
                'email_marketing' => true,
                'online_status' => false,
                'keep_signed_in' => true,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edward Clark',
                'user_name' => 'edwardclark',
                'email' => 'edward.clark@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'location_name' => 'Seattle',
                'head_line_bio' => 'Software engineer',
                'profile_image' => 'assets/profiles/profile_pic_6.png',
                'total_orders' => 15,
                'membership_level' => 'Silver',
                'email_marketing' => true,
                'online_status' => true,
                'keep_signed_in' => true,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fiona Martinez',
                'user_name' => 'fionamartinez',
                'email' => 'fiona.martinez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'female',
                'location_name' => 'Austin',
                'head_line_bio' => 'Musician',
                'profile_image' => 'assets/profiles/profile_pic_7.png',
                'total_orders' => 7,
                'membership_level' => 'Gold',
                'email_marketing' => false,
                'online_status' => false,
                'keep_signed_in' => true,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'George Wilson',
                'user_name' => 'georgewilson',
                'email' => 'george.wilson@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'location_name' => 'Denver',
                'head_line_bio' => 'Entrepreneur',
                'profile_image' => 'assets/profiles/profile_pic_8.png',
                'total_orders' => 25,
                'membership_level' => 'Platinum',
                'email_marketing' => true,
                'online_status' => true,
                'keep_signed_in' => false,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hannah Lee',
                'user_name' => 'hannahlee',
                'email' => 'hannah.lee@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'female',
                'location_name' => 'Houston',
                'head_line_bio' => 'Graphic designer',
                'profile_image' => 'assets/profiles/profile_pic_9.png',
                'total_orders' => 30,
                'membership_level' => 'Gold',
                'email_marketing' => false,
                'online_status' => true,
                'keep_signed_in' => true,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabella Smith',
                'user_name' => 'isabellasmith',
                'email' => 'isabella.smith@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'female',
                'location_name' => 'Miami',
                'head_line_bio' => 'Fitness coach',
                'profile_image' => 'assets/profiles/profile_pic_10.png',
                'total_orders' => 20,
                'membership_level' => 'Gold',
                'email_marketing' => true,
                'online_status' => false,
                'keep_signed_in' => true,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
